@hostname = localhost
@port = 7250

### Example 1: Send UnTemplated Email Notification
POST https://{{hostname}}:{{port}}/api/notifications/send
Content-Type: application/json

{
  "Recipient": "jegnzc@gmail.com",
  "Priority": "High",
  "Channel": "Email",
  "Subject": "Welcome to Our Service",
  "Body": "Hello, User1! Welcome to our service."
}

### Example 2: Send UnTemplated SMS Notification
POST https://{{hostname}}:{{port}}/api/notifications/send
Content-Type: application/json

{
  "Recipient": "+50247230567",
  "Priority": "Low",
  "Channel": "SMS",
  "Subject": null,
  "Body": "Your verification code is 123456."
}

### Example 3: Send UnTemplated Push Notification
POST https://{{hostname}}:{{port}}/api/notifications/send
Content-Type: application/json

{
  "Recipient": "fXC0dzkqDu9xUMUmndlmMD:APA91bF96d55BCQDNqbxC2JEM_mNbYITPHQDqa_7vcc_eJ1ok0FkXtiIEqwPkwrrYAinvXAIxVcVd5s4XB3VdSwcovP5vd4DVafWCdEj6sENxQOV9iqOfqOMFAeEiHUkhyR5IG2z6v3s",
  "Priority": "High",
  "Channel": "Push",
  "Subject": "New Feature Alert",
  "Body": "Check out our new feature now!"
}

### Example 4: Send UnTemplated Email Notification
POST https://{{hostname}}:{{port}}/api/notifications/send
Content-Type: application/json

{
  "Recipient": "jegnzc@gmail.com",
  "Priority": "Low",
  "Channel": "Email",
  "Subject": "Weekly Newsletter",
  "Body": "Here is our weekly newsletter."
}

### Example 5: Send UnTemplated SMS Notification
POST https://{{hostname}}:{{port}}/api/notifications/send
Content-Type: application/json

{
  "Recipient": "+50247230567",
  "Priority": "High",
  "Channel": "SMS",
  "Subject": null,
  "Body": "Your appointment is confirmed for tomorrow."
}
