@hostname = localhost
@port = 7250

### Place Order 1
POST https://{{hostname}}:{{port}}/api/orders
Content-Type: application/json

{
  "OrderNumber": "ORD0203",
  "OrderDate": "2024-05-01T10:00:00Z",
  "CustomerEmail": "jegnzc.tests@gmail.com",
  "CustomerName": "Carlos Perez",
  "TotalAmount": 150.15
}

### Place Order 2
POST https://{{hostname}}:{{port}}/api/orders
Content-Type: application/json

{
  "OrderNumber": "ORD0121",
  "OrderDate": "2024-06-30T00:00:00Z",
  "CustomerEmail": "jegnzc.tests@gmail.com",
  "CustomerName": "Pedro Ruiz",
  "TotalAmount": 1250.75
}

### Place Order 3
POST https://{{hostname}}:{{port}}/api/orders
Content-Type: application/json

{
  "OrderNumber": "ORD003",
  "OrderDate": "2024-06-30T00:00:00Z",
  "CustomerEmail": "jegnzc@gmail.com",
  "CustomerName": "Alice Johnson",
  "TotalAmount": 150.00
}

### Place Order 4
POST https://{{hostname}}:{{port}}/api/orders
Content-Type: application/json

{
  "OrderNumber": "ORD004",
  "OrderDate": "2024-06-30T00:00:00Z",
  "CustomerEmail": "jegnzc@gmail.com",
  "CustomerName": "Bob Brown",
  "TotalAmount": 175.25
}

### Place Order 5
POST https://{{hostname}}:{{port}}/api/orders
Content-Type: application/json

{
  "OrderNumber": "ORD105",
  "OrderDate": "2024-06-30T00:00:00Z",
  "CustomerEmail": "jegnzc@gmail.com",
  "CustomerName": "Charlie Davis",
  "TotalAmount": 220.00
}
