@hostname = localhost
@port = 7250

### Example 1: Send Templated Email Notification
POST https://{{hostname}}:{{port}}/api/notifications/send-templated
Content-Type: application/json

{
  "Recipient": "jegnzc@gmail.com",
  "Priority": "High",
  "Channel": "Email",
  "TemplateId": "cbc3395c-e3bb-4d55-908c-4c7ce53c0478",
  "Model": {
    "FirstName": "Melanie"
  }
}

### Example 2: Send Templated SMS Notification
POST https://{{hostname}}:{{port}}/api/notifications/send-templated
Content-Type: application/json

{
  "Recipient": "+50247230567",
  "Priority": "Low",
  "Channel": "SMS",
  "TemplateId": "18d059b8-ea89-447e-8737-770bfc39c460",
  "Model": {
    "FirstName": "Doe"
  }
}

### Example 3: Send Templated Push Notification
POST https://{{hostname}}:{{port}}/api/notifications/send-templated
Content-Type: application/json

{
  "Recipient": "fXC0dzkqDu9xUMUmndlmMD:APA91bF96d55BCQDNqbxC2JEM_mNbYITPHQDqa_7vcc_eJ1ok0FkXtiIEqwPkwrrYAinvXAIxVcVd5s4XB3VdSwcovP5vd4DVafWCdEj6sENxQOV9iqOfqOMFAeEiHUkhyR5IG2z6v3s",
  "Priority": "High",
  "Channel": "Push",
  "TemplateId": "b8619fd4-0acf-4937-8f1a-573519f22ee0",
  "Model": {
    "FirstName": "Jorge"
  }
}

### Example 4: Send Templated Email Notification
POST https://{{hostname}}:{{port}}/api/notifications/send-templated
Content-Type: application/json

{
  "Recipient": "jegnzc@gmail.com",
  "Priority": "Low",
  "Channel": "Email",
  "TemplateId": "a93c032a-22f1-419d-a659-8af289e30c0d",
  "Model": {
    "FirstName": "Pedro Lopez"
  }
}

### Example 5: Send Templated SMS Notification
POST https://{{hostname}}:{{port}}/api/notifications/send-templated
Content-Type: application/json

{
  "Recipient": "+50247230567",
  "Priority": "High",
  "Channel": "SMS",
  "TemplateId": "fcc69863-e92f-40d8-9e3d-18bc5af18845",
  "Model": {
    "FirstName": "Charlie"
  }
}
